name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Gradle Wrapper 생성
      - name: Set up Gradle Wrapper
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -P /tmp
          unzip -d /tmp /tmp/gradle-7.5.1-bin.zip
          export PATH=$PATH:/tmp/gradle-7.5.1/bin
          gradle wrapper --gradle-version 7.5.1

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle 실행 권한 부여
      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew

      # APK 빌드
      - name: Build APK
        run: ./gradlew assembleDebug

      # 빌드된 APK 업로드
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/debug/app-debug.apk
