name: Android Build

on:
  push:
    branches:
      - app1
      - app2
      
permissions:
  contents: write
  
jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check and Generate Gradle Wrapper if missing
        run: |
          if [ ! -f gradlew ]; then
            echo "Gradle Wrapper not found, generating it..."
            gradle wrapper
            chmod +x gradlew
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add gradlew gradlew.bat gradle/wrapper/
            git commit -m "Auto-generate Gradle Wrapper"
            git push origin main
          else
            echo "Gradle Wrapper already exists."
          fi
          
      - name: Cache Gradle dependencies and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --parallel --build-cache --configure-on-demand

      - name: Upload Debug APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error 
