name: Android Build and Push Gradle Wrapper

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build Android App and Push Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Gradle Wrapper 생성
      - name: Set up Gradle Wrapper
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -P /tmp
          unzip -d /tmp /tmp/gradle-7.5.1-bin.zip
          export PATH=$PATH:/tmp/gradle-7.5.1/bin
          gradle wrapper --gradle-version 7.5.1

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle 실행 권한 부여
      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew

      # APK 빌드
      - name: Build APK
        run: ./gradlew assembleDebug

      # 빌드된 APK 업로드
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Gradle Wrapper 파일을 Git에 푸시
      - name: Push Gradle Wrapper to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat
          git commit -m "Add Gradle Wrapper"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
